spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trading_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain

deribit:
  base-url: https://test.deribit.com/api/v2
  api-key: ${DERIBIT_API_KEY}
  secret-key: ${DERIBIT_SECRET_KEY}
